### PR TITLE
[#55724340] Replaced Foundation with Bootstrap

### PR DESCRIPTION
**Pull request by phirefly**

### CODE REVIEW

**Comment by jgrevich** [comment]
@phirefly I think you want to use the '3' branch of bootstrap-sass: https://github.com/thomas-mcdonald/bootstrap-sass/tree/3 no?

The master branch is still using BS2.

**Comment by jgrevich** [comment]
Also, I don't believe the 508 additions were merged into the BS2 branch.

**Comment by amoose** [comment]
Looks like the form element styles were blown out. Sorry Raphy, I forgot to mention that little tidbit. 

Testing...

**Comment by phirefly** [comment]
Closing since we opened another pull request.

**Comment by jgrevich** [comment]
Another reason why we may want to use bootstrap-sass is that we do not have to update the bootstrap assets (css/img/js) as things get updated.  Additionally I believe they fix the problem of maintaining two image dirs (assets/images and assets/img).

**Pull request closed without merging**
